import "./css/style.css";

import { Inter } from "next/font/google";
import localFont from "next/font/local";

import Header from "@/components/ui/header";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const nacelle = localFont({
  src: [
    {
      path: "../public/fonts/nacelle-regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/nacelle-italic.woff2",
      weight: "400",
      style: "italic",
    },
    {
      path: "../public/fonts/nacelle-semibold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/nacelle-semibolditalic.woff2",
      weight: "600",
      style: "italic",
    },
  ],
  variable: "--font-nacelle",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${nacelle.variable} bg-gray-950 font-inter text-base text-gray-200 antialiased`}
      >
        <div className="flex min-h-screen flex-col overflow-hidden supports-[overflow:clip]:overflow-clip">
          <Header />
          {children}
        </div>
        <script type="text/javascript">
                    (function(w, d, x, id){
                        s = d.createElement('script');
                    s.src='https://d1nv5i00u1m742.cloudfront.net/amazon-connect-chat-interface-client.js';
                    s.async=1;
                    s.id=id;
                    d.getElementsByTagName('head')[0].appendChild(s);
                    w[x] =  w[x] || function() {(w[x].ac = w[x].ac || []).push(arguments)};
  })(window, document, 'amazon_connect', '42eec3c5-848c-42ce-be5c-0ffa83b420e5');
                    amazon_connect('styles', {iconType: 'CHAT', openChat: {color: '#ffffff', backgroundColor: '#201658' }, closeChat: {color: '#ffffff', backgroundColor: '#201658'} });
                    amazon_connect('snippetId', 'QVFJREFIakNnb2I4UUFhMXdNbmZJdnEvYXJSclVQTEk0eUtlQjYvUkZmQ2Q5NU1hSWdIbWxraXo3YmJ6b0wwc1c0LzJ4bnRpQUFBQWJqQnNCZ2txaGtpRzl3MEJCd2FnWHpCZEFnRUFNRmdHQ1NxR1NJYjNEUUVIQVRBZUJnbGdoa2dCWlFNRUFTNHdFUVFNaVFWMHVNTVdOeFRKNlJIWkFnRVFnQ3NYcXFhYXkyUlY5ZTFhWmJFR2lZUkdmaWRqRjlMMFNaZEpPaGNFYi9qWHBObzVqYXlxbXRzMDJqUHk6Ok1meVRtWkl0WWdQQ1JCRXk1OFFtc0tLUEh5WWc1V1ljeVIzWjFzTVdoNEx0VDlmWEtPeFR1Q1BUMGtvUkcrd2F2b1RGaU9lSTBQQ2F5Ulg5Q1pFM0p2RE93eVM3NjlzSmtRTmFZRDNBajkxSVNBTms4Mis4TGQ2TmFOV1BjUGRBK1hKS1pXT0FVazM4K290STNKMDZLS2lIUVRaMW4vZz0=');
                    amazon_connect('supportedMessagingContentTypes', [ 'text/plain', 'text/markdown', 'application/vnd.amazonaws.connect.message.interactive', 'application/vnd.amazonaws.connect.message.interactive.response' ]);
                </script>
      </body>
    </html>
  );
}
